# Generated by Django 5.1.4 on 2025-01-28 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(default='1.0', max_length=100),
        ),
    ]
