# Generated by Django 5.1.4 on 2025-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_document_timestamp_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='qr_data',
            field=models.TextField(blank=True, help_text='Optionally store base64 or textual QR code data here.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique serial number for each stamped doc.', max_length=20, null=True),
        ),
    ]
