# Generated by Django 5.1.4 on 2025-02-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0003_document_qr_data_document_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='qr_data',
            field=models.TextField(blank=True, help_text='Stores QR code data as base64 string.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique serial number for each stamped doc.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='shape',
            field=models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Oval', 'Oval'), ('Rectangle', 'Rectangle')], max_length=20),
        ),
    ]
