# Generated by Django 5.1.4 on 2025-02-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0004_alter_document_qr_data_alter_document_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='timestamp',
        ),
    ]
